AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  microlam-java17-demo

  Sample SAM Template for microlam-java17-demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MicrolamJava17Demo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MicrolamJava17DemoNative
      CodeUri: ./target/microlam-java17-demo-1.0-SNAPSHOT-aws-lambda-native.zip
      Handler: tech.solusoft.lambda.MicrolamJava17Demo
      Runtime: provided
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        MicrolamJava17DemoApi1:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /mult
            Method: post
        MicrolamJava17DemoApi2:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sum
            Method: post
            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MicrolamJava17DemoApi:
    Description: "API Gateway endpoint URL for Prod stage for MicrolamJava17Demo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  MicrolamJava17DemoNative:
    Description: "MicrolamJava17DemoNative Function ARN"
    Value: !GetAtt MicrolamJava17DemoNative.Arn
  MicrolamJava17DemoIamRole:
    Description: "Implicit IAM Role created for MicrolamJava17DemoNative function"
    Value: !GetAtt MicrolamJava17DemoRole.Arn
